# Generated by Django 3.2.7 on 2021-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('licencia', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('ciudad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('correo', models.EmailField(max_length=30)),
            ],
        ),
    ]
