# Generated by Django 3.2.7 on 2021-10-25 15:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='zip',
        ),
        migrations.AddField(
            model_name='clientes',
            name='notas',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
