# Generated by Django 3.2.7 on 2021-10-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20211025_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='title',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Mr.', 'Mr.')], max_length=200, null=True),
        ),
    ]
