# Generated by Django 3.2.7 on 2021-11-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_auto_20211101_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='notas',
            field=models.TextField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(max_length=80),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='titulo',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Mr.', 'Mr.')], default='Mr.', max_length=200, null=True),
        ),
    ]
