# Generated by Django 3.2.7 on 2021-11-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_auto_20211102_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='notas',
            field=models.TextField(default='Pon tus anotaciones', max_length=80),
        ),
    ]
