# Generated by Django 3.2.9 on 2021-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_clientes_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
