# Generated by Django 3.2.9 on 2021-12-08 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
