# Generated by Django 3.2.9 on 2021-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_clientes_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo',
            field=models.CharField(choices=[('Corporativo', 'Corporativo'), ('Persona', 'Persona')], default='Mr.', max_length=200, null=True),
        ),
    ]
