# Generated by Django 3.2.9 on 2021-12-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_auto_20211209_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='zip',
            field=models.CharField(max_length=255),
        ),
    ]
