# Generated by Django 3.2.10 on 2022-01-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0013_alter_clientes_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='telefono2',
            new_name='telefono_2',
        ),
    ]
