# Generated by Django 3.2.10 on 2022-01-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0014_rename_telefono2_clientes_telefono_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='telefono_2',
            new_name='tel',
        ),
    ]
