# Generated by Django 3.2.10 on 2022-02-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0015_rename_telefono_2_clientes_tel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientes',
            table='Clientes',
        ),
    ]
