# Generated by Django 3.2.10 on 2022-02-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0016_alter_clientes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientes',
            table=None,
        ),
    ]
