# Generated by Django 3.2.10 on 2022-03-01 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0017_alter_clientes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='ciudad',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contacto_alternativo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contacto_alternativo2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contacto_alternativo3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='corporacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pais',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='social_media',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='social_media2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='social_media3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='titulo',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Mr.', 'Mr.')], default='Mr.', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='zip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
