# Generated by Django 3.2.10 on 2022-03-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0020_auto_20220310_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipo',
            field=models.CharField(default='Persona', max_length=200),
        ),
    ]
