# Generated by Django 3.2.10 on 2022-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0021_alter_clientes_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(blank=True, default='Mr.', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='corporacion',
            field=models.CharField(blank=True, default='Mr.', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(blank=True, default='Mr.', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo',
            field=models.CharField(max_length=200),
        ),
    ]
