# Generated by Django 3.2.10 on 2022-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0022_auto_20220310_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='corporacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
