# Generated by Django 3.2.7 on 2021-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('estatus', models.BooleanField()),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
