# Generated by Django 3.2.10 on 2022-05-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='descuento_parte',
            field=models.IntegerField(default=100),
        ),
    ]
