# Generated by Django 3.2.7 on 2021-10-25 16:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='estatus',
        ),
        migrations.AddField(
            model_name='parte',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='parte',
            name='tax_free',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='parte',
            name='total_price',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='parte',
            name='unit_price',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
