# Generated by Django 3.2.7 on 2021-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0002_auto_20211025_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='tax_free',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='total_price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='unit_price',
            field=models.IntegerField(default='0'),
        ),
    ]
