# Generated by Django 3.2.7 on 2021-11-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0003_auto_20211025_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parte',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parte',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parte',
            name='tax_free',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='parte',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parte',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
