# Generated by Django 3.2.7 on 2021-11-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0004_auto_20211101_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parte',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parte',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
