# Generated by Django 3.2.9 on 2021-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0005_auto_20211103_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='descuento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parte',
            name='total',
            field=models.IntegerField(),
        ),
    ]
