# Generated by Django 3.2.10 on 2022-01-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0006_auto_20211130_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='comprado_cliente',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='parte',
            name='resumen',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='descuento',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
