# Generated by Django 3.2.10 on 2022-01-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0007_auto_20220103_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='descuento_parte',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='resumen',
            field=models.TextField(),
        ),
    ]
