# Generated by Django 3.2.10 on 2022-01-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0008_auto_20220104_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='descuentoTotal',
            field=models.IntegerField(default='0'),
        ),
    ]
