# Generated by Django 3.2.10 on 2022-01-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0009_parte_descuentototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='descuentoTotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parte',
            name='descuento_parte',
            field=models.IntegerField(),
        ),
    ]
