# Generated by Django 3.2.10 on 2022-03-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0009_auto_20220328_2128'),
        ('Parte', '0011_auto_20220328_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='estimate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presupuestos.presupuestos'),
        ),
    ]
