# Generated by Django 3.2.12 on 2022-03-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parte', '0012_parte_estimate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='estimate_id',
        ),
    ]
