# Generated by Django 3.2.12 on 2022-03-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0013_alter_presupuestos_resumen'),
        ('Parte', '0013_remove_parte_estimate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='estimate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presupuestos.presupuestos'),
        ),
    ]
