# Generated by Django 3.2.10 on 2022-05-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0016_auto_20220505_2233'),
        ('Parte', '0016_remove_parte_estimate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='estimate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presupuestos.presupuestos'),
        ),
    ]
