# Generated by Django 3.2.10 on 2022-02-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTecnico', models.CharField(default=0, max_length=255)),
                ('emailTecnico', models.CharField(default=0, max_length=255)),
                ('telTecnico', models.IntegerField(default=0, max_length=255)),
                ('notasTecnico', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
