# Generated by Django 3.2.10 on 2022-02-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicos',
            name='apellidoTecnico',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tecnicos',
            name='corporacionTecnico',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tecnicos',
            name='telTecnico2',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='emailTecnico',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='nombreTecnico',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='notasTecnico',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='telTecnico',
            field=models.IntegerField(max_length=255),
        ),
    ]
