# Generated by Django 3.2.10 on 2022-02-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0002_auto_20220215_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnicos',
            name='corporacionTecnico',
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='apellidoTecnico',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='telTecnico2',
            field=models.IntegerField(max_length=255),
        ),
    ]
