# Generated by Django 3.2.10 on 2022-02-25 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_auto_20220218_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicos',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
