# Generated by Django 3.2.10 on 2022-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_tecnicos_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnicos',
            name='telTecnico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='telTecnico2',
            field=models.IntegerField(),
        ),
    ]
