# Generated by Django 3.2.7 on 2021-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionTiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('pais', models.CharField(choices=[('EUA', 'EUA'), ('Canada', 'Canada')], max_length=200, null=True)),
                ('zip', models.IntegerField()),
                ('ciudad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('registro', models.IntegerField()),
                ('tax_id', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('tax_for_parts', models.IntegerField()),
                ('tax_for_labor', models.IntegerField()),
                ('logo', models.ImageField(blank=True, upload_to='uploads')),
            ],
        ),
    ]
