# Generated by Django 3.2.9 on 2021-12-02 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformacionTiendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informaciontiendas',
            old_name='smtp_server',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='informaciontiendas',
            old_name='registro',
            new_name='tax_precios',
        ),
        migrations.RenameField(
            model_name='informaciontiendas',
            old_name='tax_for_labor',
            new_name='tax_productos',
        ),
        migrations.RemoveField(
            model_name='informaciontiendas',
            name='tax_for_parts',
        ),
        migrations.AddField(
            model_name='informaciontiendas',
            name='nombre_taller',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='informaciontiendas',
            name='plan',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='informaciontiendas',
            name='registro_desde',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='informaciontiendas',
            name='status',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='informaciontiendas',
            name='telefono_1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='informaciontiendas',
            name='telefono_2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='pais',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='telefono',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='zip',
            field=models.IntegerField(default='0'),
        ),
    ]
