# Generated by Django 3.2.9 on 2021-12-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformacionTiendas', '0002_auto_20211202_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaciontiendas',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='pais',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='telefono_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='telefono_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
