# Generated by Django 3.2.9 on 2021-12-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformacionTiendas', '0003_auto_20211205_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaciontiendas',
            name='nombre',
        ),
    ]
