# Generated by Django 3.2.10 on 2022-02-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformacionTiendas', '0004_remove_informaciontiendas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciontiendas',
            name='fax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='nombre_taller',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='plan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontiendas',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
