# Generated by Django 3.2.7 on 2021-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_recibido', models.ImageField(upload_to='garantias', verbose_name='Imagenes')),
                ('descripcion_recibio', models.CharField(max_length=255)),
            ],
        ),
    ]
