# Generated by Django 3.2.7 on 2021-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='descripcion_recibio',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='vehiculo_recibido',
        ),
        migrations.AddField(
            model_name='foto',
            name='imagenes',
            field=models.ImageField(default='example.jpg', upload_to='imagenes_carro', verbose_name='Imagenes'),
        ),
    ]
