# Generated by Django 3.2.7 on 2021-10-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0002_auto_20211025_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagenes',
            field=models.ImageField(default='example.jpg', upload_to='imagenes_carros', verbose_name='Imagenes'),
        ),
    ]
