# Generated by Django 3.2.10 on 2022-02-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0004_alter_foto_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
