# Generated by Django 3.2.10 on 2022-03-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0005_alter_foto_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
    ]
