# Generated by Django 3.2.7 on 2021-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_hara', models.CharField(max_length=255)),
                ('hrs', models.IntegerField()),
                ('tasa_trabajo', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('total', models.IntegerField()),
                ('operacion_laboral', models.CharField(max_length=255)),
            ],
        ),
    ]
