# Generated by Django 3.2.10 on 2022-05-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tecnico', models.CharField(default='', max_length=200)),
                ('horas', models.IntegerField()),
                ('minutos', models.IntegerField(default=0)),
                ('tarifa', models.FloatField()),
                ('tarifa_total', models.FloatField()),
                ('libre_impuestos', models.BooleanField()),
                ('estimate_ids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presupuestos.presupuestos')),
            ],
        ),
    ]
