# Generated by Django 3.2.10 on 2022-05-12 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
        ('ManoObra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manoobra',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='manoobra',
            name='tecnico_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnicos.tecnicos'),
        ),
    ]
