# Generated by Django 3.2.7 on 2021-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manoobra',
            old_name='hrs',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='manoobra',
            old_name='operacion_laboral',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='manoobra',
            old_name='que_hara',
            new_name='tecnico',
        ),
        migrations.RemoveField(
            model_name='manoobra',
            name='tasa_trabajo',
        ),
        migrations.AddField(
            model_name='manoobra',
            name='horas',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='manoobra',
            name='libre_impuestos',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='manoobra',
            name='minutos',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='manoobra',
            name='tarifa',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='manoobra',
            name='tarifa_hora',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='descuento',
            field=models.IntegerField(default='0'),
        ),
    ]
