# Generated by Django 3.2.10 on 2022-05-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0002_auto_20220512_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manoobra',
            old_name='tecnico_id',
            new_name='tecnico',
        ),
    ]
