# Generated by Django 3.2.7 on 2021-11-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0003_alter_manoobra_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoobra',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='libre_impuestos',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='minutos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='tarifa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='tarifa_hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
