# Generated by Django 3.2.7 on 2021-11-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0004_auto_20211101_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoobra',
            name='tecnico',
            field=models.CharField(choices=[('operador 1', 'operador 1'), ('operador 2', 'operador 2'), ('operador 3', 'operador 3')], default='operador 1', max_length=200, null=True),
        ),
    ]
