# Generated by Django 3.2.7 on 2021-11-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0005_alter_manoobra_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoobra',
            name='tecnico',
            field=models.CharField(choices=[('Operador 1', 'Operador 1'), ('Operador 2', 'Operador 2'), ('Operador 3', 'Operador 3')], default='Operador 1', max_length=200, null=True),
        ),
    ]
