# Generated by Django 3.2.9 on 2021-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0006_alter_manoobra_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='manoobra',
            name='tarifa_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='descuento',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
