# Generated by Django 3.2.10 on 2022-01-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0007_auto_20211217_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoobra',
            name='total',
            field=models.IntegerField(),
        ),
    ]
