# Generated by Django 3.2.10 on 2022-01-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0008_alter_manoobra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='manoobra',
            name='numeroDescuento',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='horas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='minutos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='tarifa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='tarifa_hora',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='tarifa_total',
            field=models.IntegerField(),
        ),
    ]
