# Generated by Django 3.2.10 on 2022-01-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0009_auto_20220131_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoobra',
            name='descuento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='numeroDescuento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='tecnico',
            field=models.CharField(choices=[('Operator 1', 'Operator 1'), ('Operator 2', 'Operator 2'), ('Operator 3', 'Operator 3')], default='Operator ', max_length=200, null=True),
        ),
    ]
