# Generated by Django 3.2.10 on 2022-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0010_auto_20220131_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoobra',
            name='descripcion',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='tarifa_hora',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manoobra',
            name='tecnico',
            field=models.CharField(choices=[('Operator 1', 'Operator 1'), ('Operator 2', 'Operator 2'), ('Operator 3', 'Operator 3')], default='Operator ', max_length=200),
        ),
    ]
