# Generated by Django 3.2.12 on 2022-03-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0012_auto_20220328_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manoobra',
            name='tarifa_hora',
        ),
    ]
