# Generated by Django 3.2.12 on 2022-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0015_alter_manoobra_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoobra',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
