# Generated by Django 3.2.10 on 2022-05-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0016_alter_manoobra_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manoobra',
            name='estimate_ids',
        ),
    ]
