# Generated by Django 3.2.7 on 2021-10-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Foto', '0003_alter_foto_imagenes'),
        ('ManoObra', '0003_alter_manoobra_descripcion'),
        ('Pagos', '0002_auto_20211025_1159'),
        ('Clientes', '0003_clientes_title'),
        ('carros', '0004_alter_carro_placas'),
        ('Parte', '0003_auto_20211025_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.CharField(max_length=255)),
                ('citado_por', models.CharField(max_length=255)),
                ('ajustado_por', models.CharField(max_length=255)),
                ('realizado_por', models.CharField(max_length=255)),
                ('equilibrado', models.CharField(max_length=255)),
                ('condiciones_servicio', models.CharField(max_length=255)),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.carro')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes')),
                ('foto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Foto.foto')),
                ('mano_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManoObra.manoobra')),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pagos.pagos')),
                ('parte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Parte.parte')),
            ],
        ),
    ]
