# Generated by Django 3.2.10 on 2022-05-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('tecnicos', '0001_initial'),
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.CharField(default=0, max_length=255)),
                ('descuento_parte', models.CharField(default='0', max_length=255)),
                ('total_parte', models.FloatField(blank=True, null=True)),
                ('descuentoTotal_parte', models.IntegerField(blank=True, null=True)),
                ('descuento_manaobra', models.CharField(default='0', max_length=255)),
                ('total_manaobra', models.FloatField(blank=True, null=True)),
                ('descuentoTotal_manaobra', models.IntegerField(blank=True, null=True)),
                ('resumen', models.CharField(blank=True, max_length=255)),
                ('register_time', models.CharField(blank=True, max_length=255)),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.carro')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes')),
                ('tecnicos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnicos.tecnicos')),
            ],
        ),
    ]
