# Generated by Django 3.2.10 on 2022-02-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='session_hash',
            field=models.CharField(default=0, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='stage',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
