# Generated by Django 3.2.10 on 2022-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0002_alter_presupuestos_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='total_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
