# Generated by Django 3.2.10 on 2022-05-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0003_presupuestos_total_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
