# Generated by Django 3.2.10 on 2022-02-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0004_auto_20220213_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='ajustado_por',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='citado_por',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='condiciones_servicio',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='equilibrado',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='garantia',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='realizado_por',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
