# Generated by Django 3.2.10 on 2022-05-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0004_presupuestos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestos',
            name='descuento_manaobra',
        ),
        migrations.RemoveField(
            model_name='presupuestos',
            name='descuento_parte',
        ),
    ]
