# Generated by Django 3.2.10 on 2022-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0006_auto_20220513_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CANCELED', 'canceled')], default='PENDING', max_length=20),
        ),
    ]
