# Generated by Django 3.2.10 on 2022-02-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_tecnicos_fecha_registro'),
        ('Presupuestos', '0007_auto_20220215_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='tecnicos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnicos.tecnicos'),
        ),
    ]
