# Generated by Django 3.2.10 on 2022-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0007_alter_presupuestos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CANCELED', 'canceled')], default='PENDING', max_length=10),
        ),
    ]
