# Generated by Django 3.2.10 on 2022-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0008_presupuestos_tecnicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestos',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='presupuestos',
            name='mano_obra',
        ),
        migrations.RemoveField(
            model_name='presupuestos',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='presupuestos',
            name='parte',
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='descuentoTotal_manaobra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='descuentoTotal_parte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='descuento_manaobra',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='descuento_parte',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='total_manaobra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='total_parte',
            field=models.IntegerField(default=0),
        ),
    ]
