# Generated by Django 3.2.12 on 2022-03-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0011_rename_resume_presupuestos_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='descuentoTotal_manaobra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='descuentoTotal_parte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='total_manaobra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='total_parte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
