# Generated by Django 3.2.12 on 2022-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0012_auto_20220329_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='resumen',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
