# Generated by Django 3.2.12 on 2022-04-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0013_alter_presupuestos_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='register_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
