# Generated by Django 3.2.10 on 2022-05-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0015_auto_20220505_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestos',
            name='mano_obra',
        ),
        migrations.RemoveField(
            model_name='presupuestos',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='presupuestos',
            name='parte',
        ),
    ]
