# Generated by Django 3.2.10 on 2022-02-25 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
