# Generated by Django 3.2.10 on 2022-05-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20220523_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='date_resigter',
            new_name='date_register',
        ),
    ]
