# Generated by Django 3.2.10 on 2022-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoices_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='cuentaInvoice',
            field=models.IntegerField(default=0),
        ),
    ]
