# Generated by Django 3.2.7 on 2021-10-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManoObra', '0001_initial'),
        ('Parte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGanancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otros_costos', models.CharField(max_length=255)),
                ('descuento', models.CharField(max_length=255)),
                ('mano_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManoObra.manoobra')),
                ('parte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Parte.parte')),
            ],
        ),
    ]
