# Generated by Django 3.2.10 on 2022-02-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0011_alter_carro_motor'),
        ('Foto', '0005_alter_foto_imagenes'),
        ('Pagos', '0007_alter_pagos_tipo_pago'),
        ('Clientes', '0015_rename_telefono_2_clientes_tel'),
        ('ReporteGanancias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteganancias',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='reporteganancias',
            name='otros_costos',
        ),
        migrations.AddField(
            model_name='reporteganancias',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.carro'),
        ),
        migrations.AddField(
            model_name='reporteganancias',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes'),
        ),
        migrations.AddField(
            model_name='reporteganancias',
            name='foto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Foto.foto'),
        ),
        migrations.AddField(
            model_name='reporteganancias',
            name='garantia',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='reporteganancias',
            name='pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pagos.pagos'),
        ),
    ]
