# Generated by Django 3.2.10 on 2022-03-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_quantityinventory'),
        ('ReporteGanancias', '0002_auto_20220216_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteganancias',
            name='parte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
    ]
