# Generated by Django 3.2.10 on 2022-03-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManoObra', '0011_auto_20220301_1010'),
        ('Foto', '0005_alter_foto_imagenes'),
        ('Clientes', '0023_auto_20220310_1338'),
        ('carros', '0026_auto_20220311_1049'),
        ('Pagos', '0007_alter_pagos_tipo_pago'),
        ('inventory', '0009_alter_inventory_quantityinventory'),
        ('ReporteGanancias', '0005_alter_reporteganancias_parte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteganancias',
            name='parte',
        ),
        migrations.AddField(
            model_name='reporteganancias',
            name='parteInventory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='carro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='carros.carro'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='foto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Foto.foto'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='mano_obra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ManoObra.manoobra'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='pago',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Pagos.pagos'),
        ),
    ]
