# Generated by Django 3.2.10 on 2022-03-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0007_alter_pagos_tipo_pago'),
        ('inventory', '0009_alter_inventory_quantityinventory'),
        ('carros', '0026_auto_20220311_1049'),
        ('Foto', '0005_alter_foto_imagenes'),
        ('ManoObra', '0011_auto_20220301_1010'),
        ('ReporteGanancias', '0006_auto_20220314_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteganancias',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.carro'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foto.foto'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='mano_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManoObra.manoobra'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.pagos'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='parteInventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
