# Generated by Django 3.2.10 on 2022-03-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_quantityinventory'),
        ('ReporteGanancias', '0007_auto_20220314_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteganancias',
            name='parteInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
