# Generated by Django 3.2.10 on 2022-03-21 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0023_auto_20220310_1338'),
        ('inventory', '0009_alter_inventory_quantityinventory'),
        ('ReporteGanancias', '0008_alter_reporteganancias_parteinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteganancias',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='reporteganancias',
            name='parteInventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
