# Generated by Django 3.2.7 on 2021-10-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='fecha_ingreso',
            field=models.CharField(max_length=255),
        ),
    ]
