# Generated by Django 3.2.7 on 2021-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_auto_20211025_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placas',
            field=models.CharField(max_length=20),
        ),
    ]
