# Generated by Django 3.2.9 on 2021-11-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_alter_clientes_telefono'),
        ('carros', '0004_alter_carro_placas'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='agente_seguros',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes'),
        ),
        migrations.AddField(
            model_name='carro',
            name='compañia_seguros',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='carro',
            name='no_politica',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
