# Generated by Django 3.2.9 on 2021-12-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_auto_20211130_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='agente_seguros',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='compañia_seguros',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='no_politica',
            field=models.CharField(max_length=255),
        ),
    ]
