# Generated by Django 3.2.9 on 2021-12-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_auto_20211202_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
