# Generated by Django 3.2.9 on 2021-12-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_carro_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placas',
            field=models.CharField(max_length=255),
        ),
    ]
