# Generated by Django 3.2.9 on 2021-12-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_auto_20211210_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='motor',
        ),
    ]
