# Generated by Django 3.2.10 on 2022-01-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_remove_carro_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='motor',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
