# Generated by Django 3.2.10 on 2022-02-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0013_carro_fecha_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='fecha_registro',
            new_name='fecha_registros',
        ),
    ]
