# Generated by Django 3.2.10 on 2022-03-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0014_rename_fecha_registro_carro_fecha_registros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='agente_seguros',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='compañia_seguros',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='no_politica',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
