# Generated by Django 3.2.10 on 2022-03-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0018_auto_20220228_1846'),
        ('carros', '0017_auto_20220307_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='fotosCarro',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='garantia',
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.ImageField(null=True, upload_to='images/')),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='FotosCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotosCarro', models.ImageField(null=True, upload_to='images/')),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes')),
            ],
        ),
    ]
