# Generated by Django 3.2.10 on 2022-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0018_auto_20220307_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantia',
            name='carro',
        ),
        migrations.AddField(
            model_name='carro',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='FotosCarro',
        ),
        migrations.DeleteModel(
            name='Garantia',
        ),
    ]
