# Generated by Django 3.2.10 on 2022-03-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0019_auto_20220308_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='images',
        ),
        migrations.AddField(
            model_name='carro',
            name='fotosCarro',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='carro',
            name='garantia',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
