# Generated by Django 3.2.10 on 2022-03-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0021_auto_20220309_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroimagenes',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.carro'),
        ),
        migrations.AlterField(
            model_name='garantiaimagenes',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.carro'),
        ),
    ]
