# Generated by Django 3.2.10 on 2022-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0022_auto_20220309_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroimagenes',
            name='fotosCarro',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='garantiaimagenes',
            name='garantia',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
