# Generated by Django 3.2.10 on 2022-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0023_auto_20220310_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantiaimagenes',
            name='carro',
        ),
        migrations.AddField(
            model_name='carro',
            name='fotosCarro',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='carro',
            name='garantia',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='CarroImagenes',
        ),
        migrations.DeleteModel(
            name='GarantiaImagenes',
        ),
    ]
