# Generated by Django 3.2.10 on 2022-03-11 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0023_auto_20220310_1338'),
        ('carros', '0024_auto_20220310_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='agente_seguros',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='compañia_seguros',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='fecha_registros',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='fotosCarro',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='garantia',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='motor',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='no_politica',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='vin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
