# Generated by Django 3.2.10 on 2022-03-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0025_auto_20220311_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='agente_seguros',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='compañia_seguros',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='motor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carro',
            name='no_politica',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
