# Generated by Django 3.2.10 on 2022-03-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0026_auto_20220311_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='fotosCarro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='garantia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
