# Generated by Django 3.2.7 on 2021-10-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Transferencia Bancaria', 'Transferencia Bancaria'), ('Móvil', 'Móvil'), ('QR', 'QR'), ('Criptomonedas', 'Criptomonedas')], max_length=200, null=True)),
                ('cantidad_pago', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('cantidad_pagada', models.CharField(max_length=255)),
                ('saldo_adeudado', models.CharField(max_length=255)),
            ],
        ),
    ]
