# Generated by Django 3.2.10 on 2022-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='cantidad_pagada',
            field=models.FloatField(),
        ),
    ]
