# Generated by Django 3.2.7 on 2021-10-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='cantidad_pago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='saldo_adeudado',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='total',
        ),
    ]
