# Generated by Django 3.2.7 on 2021-11-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_auto_20211025_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagos',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cantidad_pagada',
            field=models.IntegerField(),
        ),
    ]
