# Generated by Django 3.2.7 on 2021-11-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0003_auto_20211101_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Transferencia Bancaria', 'Transferencia Bancaria'), ('Móvil', 'Móvil'), ('QR', 'QR'), ('Criptomonedas', 'Criptomonedas')], default='Crédito', max_length=200, null=True),
        ),
    ]
