# Generated by Django 3.2.10 on 2022-01-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0004_alter_pagos_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='total',
        ),
        migrations.AddField(
            model_name='pagos',
            name='numero_transaccion',
            field=models.IntegerField(default='0'),
        ),
    ]
