# Generated by Django 3.2.10 on 2022-01-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0005_auto_20220103_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='numero_transaccion',
            field=models.IntegerField(),
        ),
    ]
