# Generated by Django 3.2.10 on 2022-01-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0006_alter_pagos_numero_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='tipo_pago',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('Bank Transfer', 'Bank Transfer'), ('Mobile', 'Mobile'), ('QR', 'QR'), ('Cryptocurrency', 'Cryptocurrency')], default='Crédito', max_length=200, null=True),
        ),
    ]
