# Generated by Django 3.2.12 on 2022-03-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0013_alter_presupuestos_resumen'),
        ('Pagos', '0007_alter_pagos_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presupuestos.presupuestos'),
        ),
    ]
