# Generated by Django 3.2.10 on 2022-05-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0008_pagos_estimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='estimate',
        ),
    ]
