# Generated by Django 3.2.10 on 2022-05-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0016_auto_20220505_2233'),
        ('Pagos', '0009_remove_pagos_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presupuestos.presupuestos'),
        ),
    ]
