# Generated by Django 3.2.7 on 2021-10-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0002_alter_carro_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('posicion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('vehiculos_poseidos', models.ManyToManyField(blank=True, to='carros.Carro')),
            ],
        ),
    ]
