# Generated by Django 3.2.10 on 2022-02-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
    ]
