# Generated by Django 3.2.10 on 2022-02-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220214_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='name',
            new_name='descriptionInventory',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock',
        ),
        migrations.AddField(
            model_name='inventory',
            name='codigoInventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='invoiceNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='minimumInventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantityInventory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unitPriceInventory',
            field=models.IntegerField(default=0),
        ),
    ]
