# Generated by Django 3.2.10 on 2022-02-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220218_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='codigoInventory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='invoiceNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='minimumInventory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unitPriceInventory',
            field=models.IntegerField(),
        ),
    ]
