# Generated by Django 3.2.10 on 2022-02-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220218_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('Pending', 'Pending')], default='Ok', max_length=255),
        ),
    ]
