# Generated by Django 3.2.10 on 2022-02-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('Ok', 'Ok'), ('Pending', 'Pending')], default='Ok', max_length=255),
        ),
    ]
