# Generated by Django 3.2.10 on 2022-03-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_codigoinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantityInventory',
            field=models.IntegerField(default=0),
        ),
    ]
